name: "roen_transformer_word"
joeynmt_version: "2.0.0"


data:    
    train: "sampled_data/train.ro-en"
    dev:   "sampled_data/dev.ro-en"
    test:  "sampled_data/test.ro-en"
    dataset_type: "plain"
    src:
        lang: "ro"
        level: "word"
        lowercase: False
        max_length: 100
        #max_sent_length: 100
        # Using a vocabulary limit:
        voc_limit: 2000
        tokenizer_cfg:
            pretokenizer: "moses"
    trg: 
        lang: "en"
        level: "word"
        lowercase: False
        max_length: 100
        #max_sent_length: 100
        # Using a vocabulary limit:
        voc_limit: 2000
        tokenizer_cfg:
            pretokenizer: "moses"

testing:
    beam_size: 5
    beam_alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    learning_rate: 0.0003
    batch_size: 2048
    batch_type: "token"
    eval_batch_size: 1024
    eval_batch_type: "token"
    scheduling: "plateau"
    patience: 8
    weight_decay: 0.0
    decrease_factor: 0.7
    early_stopping_metric: "ppl"
    epochs: 10
    validation_freq: 500
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/roen_transformer_word"
    overwrite: False
    shuffle: True
    use_cuda: False
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3, 4]
    label_smoothing: 0.3

model:
    initializer: "xavier_uniform"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier_uniform"
    embed_init_gain: 1.0
    #Set to false since target and source languages don't share vocabulary.
    tied_embeddings: False
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 4
        num_heads: 2
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0
        hidden_size: 256
        ff_size: 512
        dropout: 0
    decoder:
        type: "transformer"
        num_layers: 1
        num_heads: 2
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0
        hidden_size: 256
        ff_size: 512
        dropout: 0
